# Generated by Django 6.0.7 on 2026-08-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
